ignore_colors = [
	[0, 0, 0, 0],
	[255, 255, 255, 0],
	# [0, 0, 0, 255], # filter all black
]
version = 2.3
pixel_file = "pixel.json"

# priority: higher number = higher chance of being placed
[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "seele"
file = "images/seele.png"
startx = 650
starty = 1400
priority = 1